version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sang111/cook-assistant-spring:0.1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
